"""Generate record type registry from schemas.

Output: python/src/pyjvlink/protocol/generated/registry.py
"""

from __future__ import annotations

from .schema_loader import load_all_schemas

HEADER = """\
# WARNING: This file is auto-generated by scripts/codegen.
# Do not edit manually. Changes will be overwritten.
# Source: protocol/schema/records/*.json

from __future__ import annotations
"""


def generate_registry() -> str:
    """Generate the full content of protocol/generated/registry.py."""
    schemas = load_all_schemas()
    parts: list[str] = [HEADER]

    # Generate RECORD_TYPES set (ruff-compatible frozenset format)
    types = sorted(schemas.keys())
    parts.append("RECORD_TYPES: frozenset[str] = frozenset(")
    parts.append("    {")
    for rt in types:
        title = schemas[rt]["title"]
        parts.append(f'        "{rt}",  # {title}')
    parts.append("    }")
    parts.append(")")

    # Generate KEY_FIELDS mapping
    parts.append("")
    parts.append("")
    parts.append("KEY_FIELDS: dict[str, tuple[str, ...]] = {")
    for rt in types:
        keys = schemas[rt]["key_fields"]
        keys_str = ", ".join(f'"{k}"' for k in keys)
        # Single-element tuples need a trailing comma to avoid being parsed as str
        if len(keys) == 1:
            keys_str += ","
        line = f'    "{rt}": ({keys_str}),'
        if len(line) > 120:
            # Split across multiple lines
            parts.append(f'    "{rt}": (')
            for k in keys:
                parts.append(f'        "{k}",')
            parts.append("    ),")
        else:
            parts.append(line)
    parts.append("}")

    return "\n".join(parts) + "\n"
