"""Generate formatter metadata from record schemas.

Output: python/src/pyjvlink/protocol/generated/formatter_meta.py
"""

from __future__ import annotations

from typing import Any

from .schema_loader import load_all_schemas, resolve_fields

HEADER = '''\
# WARNING: This file is auto-generated by scripts/codegen.
# Do not edit manually. Changes will be overwritten.
# Source: protocol/schema/records/*.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class FieldMeta:
    """Metadata for a single record field, used for formatting and display."""

    name: str
    item_number: int
    label: str
    semantic_type: str
    unit: str | None = None
'''


def _field_meta_repr(field: dict[str, Any]) -> str:
    """Generate a FieldMeta constructor call for a field."""
    name = field["name"]
    item_number = field["item_number"]
    label = field.get("display", {}).get("label", name)
    st = field["semantic_type"]
    unit = field.get("unit")

    parts = [
        f'        FieldMeta("{name}", {item_number}, "{label}", "{st}"',
    ]
    if unit:
        parts[0] += f', unit="{unit}"'
    parts[0] += "),"
    return parts[0]


def generate_formatter_meta() -> str:
    """Generate the full content of protocol/generated/formatter_meta.py."""
    schemas = load_all_schemas()
    parts: list[str] = [HEADER]

    parts.append("\nFORMATTER_META: dict[str, list[FieldMeta]] = {")

    for rt in sorted(schemas.keys()):
        schema = schemas[rt]
        all_fields = resolve_fields(schema)

        parts.append(f'    "{rt}": [')
        for field in all_fields:
            parts.append(_field_meta_repr(field))
        parts.append("    ],")

    parts.append("}")

    return "\n".join(parts) + "\n"
